name: Daily Joke Poem Email

on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8:00（北京时间16:00）发送
  workflow_dispatch:  # 支持手动触发

jobs:
  send-email:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 设置超时时间
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 更新到最新版本
        
      - name: Set up Python
        uses: actions/setup-python@v5  # 更新到最新版本
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
      
      # 更可靠的环境变量检查
      - name: Verify environment variables
        run: |
          echo "EMAIL_USER length: ${#EMAIL_USER}"
          echo "EMAIL_PASS length: ${#EMAIL_PASS}"
          echo "TO_EMAIL value: $TO_EMAIL"
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          
      - name: Run email script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python email_bot.py
        
      # 更新后的日志上传步骤（使用v4版本）
      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4  # 修正为当前支持的版本
        with:
          name: email-bot-logs
          path: email.log
